In [1]:
v <- c(1,2,3,4,5)

In [2]:
v[2]

[1] 2

In [3]:
mat <- matrix(1:50, byrow = T, nrow = 5)

In [4]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [5]:
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [6]:
mat[,5]

[1]  5 15 25 35 45

In [7]:
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [11]:
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [13]:
mat[,6:7]

[,1] [,2]
[1,]  6    7  
[2,] 16   17  
[3,] 26   27  
[4,] 36   37  
[5,] 46   47