In [2]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
v <- 1:10

In [4]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [5]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [6]:
matrix(v,nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [7]:
matrix(1:12,byrow = FALSE, nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [8]:
matrix(1:12,byrow = T, nrow = 4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [9]:
TSMC <- c(189,191,193,192,195)
HTC  <- c(800,752,750,630,500)

In [10]:
stocks <- c(TSMC,HTC)
stock.matrix <- matrix(stocks,byrow = T,nrow = 2)
print(stock.matrix)

     [,1] [,2] [,3] [,4] [,5]
[1,]  189  191  193  192  195
[2,]  800  752  750  630  500


In [11]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('TSMC','HTC')
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

In [12]:
stock.matrix

Mon Tue Wed Thu Fri
TSMC 189 191 193 192 195
HTC  800 752 750 630 500