In [1]:
mat <- matrix(1:25,byrow = T,nrow = 5)

In [2]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [3]:
mat*2

[,1] [,2] [,3] [,4] [,5]
[1,]  2    4    6    8   10  
[2,] 12   14   16   18   20  
[3,] 22   24   26   28   30  
[4,] 32   34   36   38   40  
[5,] 42   44   46   48   50

In [4]:
mat/2

[,1] [,2] [,3] [,4] [,5]
[1,]  0.5  1.0  1.5  2.0  2.5
[2,]  3.0  3.5  4.0  4.5  5.0
[3,]  5.5  6.0  6.5  7.0  7.5
[4,]  8.0  8.5  9.0  9.5 10.0
[5,] 10.5 11.0 11.5 12.0 12.5

In [5]:
mat^2

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [6]:
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000

In [7]:
mat >10

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [9]:
mat[mat>15]

[1] 16 21 17 22 18 23 19 24 20 25

In [10]:
mat + mat

[,1] [,2] [,3] [,4] [,5]
[1,]  2    4    6    8   10  
[2,] 12   14   16   18   20  
[3,] 22   24   26   28   30  
[4,] 32   34   36   38   40  
[5,] 42   44   46   48   50

In [11]:
mat/mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [12]:
mat + 1

[,1] [,2] [,3] [,4] [,5]
[1,]  2    3    4    5    6  
[2,]  7    8    9   10   11  
[3,] 12   13   14   15   16  
[4,] 17   18   19   20   21  
[5,] 22   23   24   25   26

In [13]:
mat * mat

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [15]:
mat %*% mat

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775